services:

  frontend:
    container_name: frontend
    build: ./client/.
    ports:
      - "9999:9999"
    volumes:
      - ./client:/app
    depends_on:
      - backend
    env_file:
      - .env
    restart: always

  backend:
    container_name: api
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api/src:/app/src:ro
      - ./api/uploads:/app/uploads
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    
    
  
  db:
    container_name: database
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080


volumes:
  db-data: